
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;
	private global::Gtk.Button button_up;
	private global::Gtk.Button button_right;
	private global::Gtk.Button button5;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.HeightRequest = 250;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.WidthRequest = 60;
		this.button1.HeightRequest = 60;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Launch");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w1.X = 164;
		w1.Y = 92;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button ();
		this.button2.WidthRequest = 60;
		this.button2.HeightRequest = 60;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Down");
		this.fixed1.Add (this.button2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button2]));
		w2.X = 163;
		w2.Y = 159;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_up = new global::Gtk.Button ();
		this.button_up.WidthRequest = 60;
		this.button_up.HeightRequest = 60;
		this.button_up.CanFocus = true;
		this.button_up.Name = "button_up";
		this.button_up.UseUnderline = true;
		this.button_up.Label = global::Mono.Unix.Catalog.GetString ("Up");
		this.fixed1.Add (this.button_up);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button_up]));
		w3.X = 164;
		w3.Y = 24;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_right = new global::Gtk.Button ();
		this.button_right.WidthRequest = 60;
		this.button_right.HeightRequest = 60;
		this.button_right.CanFocus = true;
		this.button_right.Name = "button_right";
		this.button_right.UseUnderline = true;
		this.button_right.Label = global::Mono.Unix.Catalog.GetString ("Right");
		this.fixed1.Add (this.button_right);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button_right]));
		w4.X = 231;
		w4.Y = 92;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button5 = new global::Gtk.Button ();
		this.button5.WidthRequest = 60;
		this.button5.HeightRequest = 60;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Left");
		this.fixed1.Add (this.button5);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button5]));
		w5.X = 96;
		w5.Y = 91;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 329;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.Launch);
		this.button2.Pressed += new global::System.EventHandler (this.MoveDown);
		this.button2.Released += new global::System.EventHandler (this.Stop);
		this.button_up.Released += new global::System.EventHandler (this.Stop);
		this.button_up.Pressed += new global::System.EventHandler (this.MoveUp);
		this.button_right.Released += new global::System.EventHandler (this.Stop);
		this.button_right.Pressed += new global::System.EventHandler (this.MoveRight);
		this.button5.Pressed += new global::System.EventHandler (this.MoveLeft);
		this.button5.Released += new global::System.EventHandler (this.Stop);
	}
}
